In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
import json
%matplotlib inline

In [4]:
import requests
# fetch data from github
url = 'https://raw.githubusercontent.com/alvinwilta/Seleksi-2021-Tugas-1/main/Data%20Storing/export/collection.json'
resp = requests.get(url)
data = json.loads(resp.text)
df = pd.DataFrame(data)

In [7]:
import pymongo
# fetch data from local mongodb server
url = "mongodb://localhost:27017/"
client = pymongo.MongoClient(url)
db = client["basdat"]
col = db["jobs"]
data = list(col.find({}))
df = pd.DataFrame(list(data))

In [8]:
df

,_id,title,company,location,estimate_salary,exp_min,exp_opt,last_updated,applicant
0,6106ed2b79e63f3562b29d66,Solution Architect,mHealthBank,Jakarta,SGDÂ 25.000.000 - 35.000.000,5.0,10.0,9 bulan yang lalu,119.0
1,6106ed2b79e63f3562b29d67,Quality Assurance,Cv. Konsultan Teknologi Indonesia,Jakarta,IDRÂ 10.000.000 - 12.000.000,1.0,3.0,kemarin,338.0
2,6106ed2b79e63f3562b29d68,Remote Senior Full Stack Developer focused on ...,Resync Technologies,Jakarta,IDRÂ 0 - 20.000.000,5.0,10.0,14 hari yang lalu,18.0
3,6106ed2b79e63f3562b29d69,Backend Game Programmer,Anantarupa Studios,Jakarta,Login to view estimated salary by Glints.,1.0,3.0,2 hari yang lalu,49.0
4,6106ed2b79e63f3562b29d6a,Security Engineer,PT. Cudo Communications,Jakarta,IDRÂ 6.000.000 - 8.000.000,3.0,5.0,kemarin,27.0
...,...,...,...,...,...,...,...,...,...
235,610ec4e314c25900afea586c,Senior Android Developer,PT. Indo Teknologi Utama,Jakarta,IDRÂ 20.000.000 - 25.000.000,5.0,10.0,9 jam yang lalu,119.0
236,610ec4e314c25900afea586d,MOBILE DEVELOPER,PT Kwadran Lima Mitra Kaya Solusi,"TB Simatupang, Jakarta",IDRÂ 5.000.000 - 7.000.000,1.0,3.0,10 jam yang lalu,2.0
237,610ec4e314c25900afea586e,Production Environment,PT. Cudo Communications,Jakarta,IDRÂ 4.000.000 - 12.000.000,1.0,3.0,5 hari yang lalu,3.0
238,610ec4e314c25900afea586f,Java Developer (Backend),My Hunter,Jakarta,IDRÂ 5.000.000 - 10.000.000,1.0,3.0,12 jam yang lalu,29.0
239,610ec4e314c25900afea5870,Senior Network Engineer,PT Phillip Sekuritas Indonesia,Jakarta,None,1.0,3.0,13 jam yang lalu,55.0